apiVersion: v1 
kind: ConfigMap 
metadata: 
  name: cart 
  namespace: roboshop 
  labels:
    project: roboshop
    service: cart
    tier: backend
data:
  REDIS_HOST: "redis"
  CATALOGUE_HOST: "catalogue"
  CATALOGUE_PORT: "8080"
---
apiVersion: v1 
kind: Service
metadata:
  name: cart
  namespace: roboshop
  labels:
    project: roboshop
    service: cart
    tier: backend
spec:
  selector:
    project: roboshop
    service: cart
    tier: backend
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: cart 
  namespace: roboshop
  labels:
    project: roboshop
    service: cart
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      service: cart
      tier: backend
    template:
      metadata:
        labels:
          project: roboshop
          service: cart
          tier: backend
      spec: 
        containers:
          - name: cart
            image: anuragbojja/cart:v1
            imagePullPolicy: Always
            envFrom:
              configMapRef:
                - name: cart 
            livenessProbe:
              httpGet:
                path: /health
                port: 8080
              initialDelaySeconds: 15
              periodSeconds: 10
            readinessProbe:
              httpGet:
                path: /health
                port: 8080
              initialDelaySeconds: 15
              failureThreshold: 2
              periodSeconds: 10
            resources:
              requests:
                memory: "128Mi"
                cpu: "250m"
              limits:
                memory: "256Mi"
                cpu: "350m"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cart
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cart
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
