apiVersion: v1
kind: ConfigMap 
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    project: roboshop
    service: catalogue
    tier: backend
data:
  MONGO: "true"
  MONGO_URL: "mongodb://mongodb:27017/catalogue"
---
apiVersion: v1 
kind: Service
metadata: 
  name: catalogue
  namespace: roboshop
spec:
  selector:
    project: roboshop
    service: catalogue
    tier: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: catalogue
  namespace: roboshop
  labels:
    project: roboshop
    service: catalogue
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      service: catalogue
      tier: backend
  template:
      metadata:
        labels:
          project: roboshop
          service: catalogue
          tier: backend
      spec:
        containers:
          - name: catalogue
            image: anuragbojja/catalogue:v1
            imagePullPolicy: Always 
            livenessProbe:
              httpGet:
                path: /health
                port: 8080
              initialDelaySeconds: 15
              periodSeconds: 10
            readinessProbe:
              httpGet:
                path: /health
                port: 8080
              initialDelaySeconds: 15
              failureThreshold: 2
              periodSeconds: 10
            envFrom:
              - configMapRef:
                  name: catalogue
            resources:
              requests:
                memory: "128Mi"
                cpu: "250m"
              limits:
                memory: "256Mi"
                cpu: "350m"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    project: roboshop
    service: catalogue
    tier: backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: catalogue
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50